### ISSUE TITLE
Which hardware?

### ISSUE THREAD

**Issue by FrancescoTalotta** [DanieleSgroi/ARINC-429-TX#1]
Hello,

do you think your implementation can work with the transmitter schematics found here (page 13):

https://www.dropbox.com/s/ath30pu0fsyf33x/Arinc%20429%20decoding%20with%20Raspberry%20Pi.docx?dl=0 

or a HI-8585 could work?

Thank you

**Comment by DanieleSgroi** [comment]
Hallo Francesco,

my code has been successfully tested with a HI-8585 line driver and some real avionic equipment.

The circuit provided in the document you have referenced should work, but it does not provide correct differential signal levels at the ARINC-429 line side. 

For this reason, compatibility with standard receivers can't be guaranteed.

Ciao

Daniele

**Comment by FrancescoTalotta** [comment]
Hello Daniele, 

Thank you for your quick reply!

Yes, actually I was thinking the same, that simple circuit does not provide differential signals. So I will try with a HI-8585. Any idea on how to provide +15V/-15V? I read about virtual ground with several possible implementations. Do you suggest some particular solution for this?

Thanks

Ciao

Francesco

**Comment by DanieleSgroi** [comment]
I did my breadboarding (see attached image) using a Murata NMK0515SC DC/DC converter: it takes a 5V and provides dual output at +15/-15V for the ARINC line drivers.
Unfortunately, for my home projects, I was only able to source cheap (chinese clones?) of HI-8585/6 line driver (and HI-8588 receiver).
If you have any chance to source directly form HOLT, you can look at the HI-8593 that only requires a single +5V to operate, thus easier to be directly interfaced to a 5V Arduino.
Proper receiving, including timing and error checking, is more difficult than transmission, so I shame to publish that part of the code ;-)
Keep in mind that Arduino may not be powerful enough to handle complex multi-label transmissions with live data at high data rates: in this case I would suggest upgrading to a Teensy 4.x.
![PXL_20211219_134846797](https://user-images.githubusercontent.com/23435217/146677474-301bfd26-2914-4c12-8c1e-c701b7990792.jpg)

**Comment by FrancescoTalotta** [comment]
Hello again,

thank you. I will try this solution with a NMK0515SC. I had some problems using Arduino as it is slow to transmit and receive data. For this reason I want to translate your implementation using pure AVR-C. 

Well, if you want to share the RX part, I would be very happy!! 💯 :) 

Thanks again

**Comment by DanieleSgroi** [comment]
As you can see, my implementation is already accessing low-level registers to minimize execution time and jittering within the time-critical sections. For this reason I don't think it could be further optimized, and this is the reason why I warned about performances, not to mention the possibility to transmit AND receive simultaneously.
What are you trying to achieve?

**Comment by FrancescoTalotta** [comment]
Yes I see actually the A429Out has low level instructions. I would like to interface some real avionics with MSFS using ARINC 429. I now have a Thales digital altimeter and I would like to make it work. My idea is to use some electronics I have developed already that use ATMEGA or ATTINY processors. This electronics is able to send and receive data from the PC to the boards via serial communication (19200 bps). The last part I need to implement is sending and receiving ARINC signals to the avionics.

**Comment by DanieleSgroi** [comment]
I did something similar in the past for a homemade "test jig" for some Collins COM and NAV radios. 
With "burst" tuning, bit-banging was enough because the Arduino only had to transmit when you tune a new frequency. 
Receiving was at a low data rate and "relaxed" (on the order of few labels every 500 msec).
Everything depends on the amount of data you have to exchange with your altimeter. Do you have the full ICD? I suppose you need to send at least the QNH and receive some labels. The amount of data and their rate is what makes it difficult.
With bit-banging, the CPU is just shifting a register for the entire TX duration of the 32 bits of an ARINC word (at 12,5 kbps a word TX last 2,56 msec). It is a big waste of time, and with interrupts disabled to keep the correct bit timing you can't do anything more than waiting.
At minimum, I would convert the code attaching an interrupt to a timer to take care of the TX shift-register and output. 
This will save a lot of time to do other things: you just write the TX register and go ahead with your code. 
Real things use FIFOs to prepare a whole packet of N x ARINC words.
Reception shall be done entirely via interrupts: I've attached two ISR's (one to Input A, the other to Input B from the line receiver) to recover the clock, but it is really difficult to perform all the checks required by the standard. 
Not only a parity check, I mean bit sampling, overruns, bit rate, inter word gap time, etc. If you can skip some of these, things become easier.
Real things use custom devices or FPGAs with FIFOs to let the CPU process only what is already correctly received.
Good luck!
